### ISSUE TITLE
 Controller Spawner couldn't find the expected controller_manager ROS interface

### ISSUE THREAD

**Issue by 1140452** [AutoRally/autorally#78] opened 2019-03-29 12:06 UTC
Hello I installed your repo and trying to run the `roslaunch autorally_gazebo autoRallyTrackGazeboSim.launch`  and this warn appears: 

![Screenshot from 2019-03-29 12-05-39](https://user-images.githubusercontent.com/44970132/55231619-26334680-521b-11e9-9add-0cc4cac54f23.png)

[WARN] [1553860760.215555, 0.000000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[controller_spawner-6] process has finished cleanly
log file: /home/daniel/.ros/log/03184c32-521a-11e9-af93-1831bf747ba9/controller_spawner-6*.log
[spawn_platform-5] process has finished cleanly
log file: /home/daniel/.ros/log/03184c32-521a-11e9-af93-1831bf747ba9/spawn_platform-5*.log

Do you know how to fix this, because I'm being able to get anything in any simulation to work. thx.

**Comment by Chufan1990** [comment] 2019-04-04 04:06
@1140452 did you fix it? I have the same issue as you.

**Comment by 1140452** [comment] 2019-04-04 10:20
Hello, yes i did managed to solve the problem. As I was searching for solutions and it turned out to be memory problems, as the pc couldn't handle all the processing from the simulation. 
To solve it I deleted the cloud rendering they have in _populated_marietta.world_ and it was done.

**Comment by jisacks** [comment] 2019-04-04 21:56
I have this issue as well. When I manually launch the spawner as per the launch file after Gazebo has been launched, I am able to properly control the car. This problem seemed to appear out of nowhere, as I had not updated anything on my machine. I also don't know why it can't seem to launch the spawner properly within the launch file.

**Comment by djhanove** [comment] 2019-06-16 23:00
Deleting clouds did not work. Had to launch the controller once gazebo finished opening as well @jsacks3 
Edit: I just forked today. This feels like it is probably buried in some obscure LTS update for kinetic ROS controllers

**Comment by JasonGibson274** [comment] 2019-07-10 23:26
Can anyone who is having this issue give me your version of

Ubuntu
Gazebo

I am unable to reproduce this on my machine, but I have seen it happen on others.

**Comment by 1140452** [comment] 2019-07-10 23:36
> Can anyone who is having this issue give me your version of
> 
> Ubuntu
> Gazebo
> 
> I am unable to reproduce this on my machine, but I have seen it happen on others.

In my case was Ubuntu 16.04 and Gazebo 7

**Comment by JasonGibson274** [comment] 2019-07-10 23:49
Can you confirm that this package is installed?  ros-kinetic-gazebo-ros-control

Also that you are on the latest version of kinetic-devel

along with that if you run a launch file with the contents below after gazebo has launched does it fix the issue?

```
<?xml version="1.0"?>
<launch>

  <!-- Load the joint controllers. One of these publishes the joint states to joint_states. -->
  <node name="controller_spawner" pkg="controller_manager" type="spawner"
        args="$(find autorally_gazebo)/config/autoRallyPlatformJointCtrlrParams.yaml"/>

  <!-- Control the steering, axle, and shock absorber joints. -->
  <node name="autorally_controller" pkg="autorally_gazebo"
        type="autorally_controller.py" output="screen">
    <param name="cmd_timeout" value="0.5"/>
    <rosparam file="$(find autorally_gazebo)/config/autoRallyPlatformCtrlrParams.yaml" command="load"/>
  </node>


</launch>
```

**Comment by 1140452** [comment] 2019-07-11 00:08
I have that package installed and that error does appear when trying to run your launch file. However it stops appearing when I make it to launch the world and the car.

**Comment by JasonGibson274** [comment] 2019-07-11 00:14
So if the world is launched and up before the controllers are spawned it works just fine?

**Comment by JasonGibson274** [comment] 2020-06-12 17:53
Try running with verbose enabled in the track launch file

**Comment by keuntaeklee** [comment] 2020-10-10 01:24
Installing these ros packages solved the same issue:

sudo apt-get install ros-kinetic-ros-control ros-kinetic-joint-state-controller ros-kinetic-effort-controllers ros-kinetic-position-controllers ros-kinetic-velocity-controllers ros-kinetic-ros-controllers ros-kinetic-gazebo-ros ros-kinetic-gazebo-ros-control

**Comment by JasonGibson274** [comment] 2021-02-04 21:53
Closing this issue for now. Please reopen if the problem persists

**Closed as completed by JasonGibson274** 2021-02-04 21:53 UTC
